### ISSUE TITLE
Nimiq script should not be removed after loading

### ISSUE THREAD

**Issue by sisou** [nimiq/app-starter-kit#8]
Why is the script that loaded the Nimiq lib removed onload? I think it should not.
https://github.com/nimiq/app-starter-kit/blob/83df24a97cfd8b7027fede089aeb41c8d2cd48ad/src/lib/CoreLoader.ts#L30-L31

**Comment by danimoh** [comment]
For clean up. Is it doing any harm?

**Comment by danimoh** [comment]
Removing the script works fine, but to avoid that users get confused, I removed this now.
